### ISSUE TITLE
Error! Probably not a good sign, but try again.

### ISSUE THREAD

**Issue by SC7639** [sotojuan/is-pokemon-go-up-cli#3]
Each time I try to run it i just keep getting "Error! Probably not a good sign, but try again."
```
> is-pokemon-go-up
Error! Probably not a good sign, but try again.
```

I'm using Node ``` v5.3.0``` and I'm on windows
```
> where is-pokemon-go-up
C:\Users\SCrossan\AppData\Roaming\npm\is-pokemon-go-up
C:\Users\SCrossan\AppData\Roaming\npm\is-pokemon-go-up.cmd
```

**Comment by sotojuan** [comment]
Hey sorry, I really should've put this in the readme. We use `curl` to make the request to the servers, which doesn't exist on Windows. There's an easy way to fix this, and I'll get to it soon. Sorry again!

**Comment by SC7639** [comment]
Hi,

I've tried it again in Git Bash which does have ```curl``` but I'm still getting the same. I've even tried it in docker
```
$ curl
curl: try 'curl --help' or 'curl --manual' for more information
```
```
$ is-pokemon-go-up
Error! Probably not a good sign, but try again.
```
Docker output Gist
https://gist.github.com/SC7639/fbb96f5c0d7320b483d464dd82d98a6b

**Comment by sotojuan** [comment]
Ah, weird. Sorry, It works for me :/ I'll look into it later after work.

**Comment by SC7639** [comment]
Ok thanks. It's not a huge deal but I'd love to be able to use your tool thanks.

**Comment by bryandowning** [comment]
Maybe you need to commit index.js?

**Comment by sotojuan** [comment]
Closing for now, reopen if more errors come up!
